name: Deploy to Google Cloud

on:
  push:
    branches:
      - master  # Ensure this matches your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to the latest version
      with:
        node-version: '20'

    - name: Set environment variable
      run: echo "REACT_APP_BACKEND_URL=${{ secrets.BACKEND_URL }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Build the project
      env:
        REACT_APP_BACKEND_URL: ${{ secrets.BACKEND_URL }}
      run: CI=false npm run build  # Disable treating warnings as errors

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # Updated to the latest version
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet